version: '3.9'

services:
  poke.api:
    image: poke.api
    container_name: poke.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - poke.database
    environment:
      - ConnectionStrings__PokeDb=Host=poke.database;Database=poke;Username=admin;Password=P@ssw0rdP@ssw0rd

  poke.database:
    image: postgres:latest
    container_name: poke.database
    environment:
      POSTGRES_DB: poke
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rdP@ssw0rd
    volumes:
      - poke-database-volume:/var/lib/postgresql/data
    ports:
      - "5005:5432"

volumes:
  poke-database-volume:
